from typing import Final, Tuple
Y_ORDER: Final[Tuple[str, ...]]
AUX_ORDER: Final[Tuple[str, ...]]
NY: Final[int]
NAUX: Final[int]
A_p0: Final[int]
I_m01: Final[int]
I_m12: Final[int]
I_m13: Final[int]
I_p1: Final[int]
P_C1: Final[int]
P_a01: Final[int]
P_a12: Final[int]
P_a13: Final[int]
P_j01: Final[int]
P_j12: Final[int]
P_j13: Final[int]
P_p2: Final[int]
P_p3: Final[int]
P_pf_tnk: Final[int]
P_po_tnk: Final[int]
P_rf_amp_2: Final[int]
P_rhoFu: Final[int]
